version: "3.7"
services:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tia
      MYSQL_USER: srodriguez
      MYSQL_PASSWORD: srodriguez
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

volumes:
  mysql-data:
